In [1]:
import numpy as np

In [2]:
lista = [1, 2, 3, 4, 5, 6, 7, 8, 9]
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [5]:
arr = np.array(lista)

In [6]:
type(arr)

numpy.ndarray

In [7]:
matriz = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
matriz = np.array(matriz)
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
arr[0] + arr[5]

7

In [11]:
matriz 

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
matriz[0, 2]

3

In [14]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

SLICING

In [15]:
arr[1:6]

array([2, 3, 4, 5, 6])

In [16]:
arr[:6]

array([1, 2, 3, 4, 5, 6])

Traer todo en una secuencia especificada

In [17]:
arr[::3]

array([1, 4, 7])

In [18]:
arr[-1]

9

In [19]:
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
matriz[1:]

array([[4, 5, 6],
       [7, 8, 9]])

In [27]:
matriz[1:, 0:3]

array([[4, 5, 6],
       [7, 8, 9]])